#spring:
#  datasource:
#       generate-unique-name: false  Bunu her seferinde database adı oluşturmamak için kullandık.
#    url: jdbc:h2:file:./db/devdb
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#//



spring:
  datasource:
       generate-unique-name: false
       
Spring:
   jpa:
      properties:
         jakarta: 
            persistence:
               validation:
                  mode: none
   data:
      web:
         pageable:
               default-page-size: 3
               max-page-size: 8
   jackson:
      mapper:
         DEFAULT_VIEW_INCLUSION: true
            
             
            
    
# Aşağıdaki şekillerde loglevellerini belirlelyip istediğimiz seviyede log tutup hata vb. kontrolünü yapabiliriz.              
#logging: 
#   level:
#      org.springframework: DEBUG
#      
#logging:
#  level:
#    com.example.packageName: INFO  # Belirli bir paketin log seviyesini INFO olarak ayarlayın
#    another.packageName: WARN     # Başka bir paketin log seviyesini WARN olarak ayarlayın


   