spring:
  datasource:
    #   generate-unique-name: false  Bunu her seferinde database adı oluşturmamak için kullandık.
    url: jdbc:h2:file:./db/devdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
